version: '3.8'

services:
  backend:
    build: ./backend-registro-personas
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - app-network
    restart: on-failure

  frontend:
    build: ./frontend-registro-personas
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personas
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      #- ./CRUD-PERSONAS/personas.sql:/docker-entrypoint-initdb.d/personas.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
